auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn # Reducir verbosidad en producción

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 30m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 720h # 30 días
  retention_stream:
    - selector: '{level="debug"}'
      priority: 3
      period: 24h
    - selector: '{level="info"}'
      priority: 2
      period: 168h # 7 días
