server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs de contenedores Docker
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: service
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_task_name]
        target_label: task
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_task_slot]
        target_label: slot
      - source_labels: [__meta_docker_container_label_com_docker_swarm_node_id]
        target_label: node
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

  # Logs del sistema y host
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.log
