name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/nahuelrocha/academia2025-challenge:${{ env.TAG }}
            ghcr.io/nahuelrocha/academia2025-challenge:latest
          cache-from: type=registry,ref=ghcr.io/nahuelrocha/academia2025-challenge:cache
          cache-to: type=registry,ref=ghcr.io/nahuelrocha/academia2025-challenge:cache,mode=max

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/nahuelrocha/academia2025-challenge:${{ env.TAG }}"
          format: "table"
          exit-code: "0"
          severity: "CRITICAL"
